engines:
  rubocop:
    enabled: true
    config: config/rubocop/src.yml
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
    config:
      config: sites/config/eslint_for_codeclimete.json

ratings:
  paths:
   - src/**/*.rb
   - sample_agents/**/*.rb
   - sites/src/js/**/*.js
   - Gemfile.lock

exclude_paths:
  - spec/**/*
  - rest_spec/**/*
  - sites/spec/**/*
  - sites/node_modules
  - sites/build
  - sites/config
  - sites/lib
  - Rakefile
